 # .goreleaser.yaml
project_name: portail

builds:
  - main: ./cmd/portail/main.go
    goos: [linux, windows, darwin]
    goarch: [amd64, arm64]
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE
      - config.yaml

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"

release:
  github:
    owner: chaurasiayush
    name: portail
